DATASET:
  TEST:
    DATASET_LIST:
    - TARGET
    EPOCH_SIZE: 4950
    TARGET:
      DATA_SPLIT: test
      EPOCH_SIZE: 4950
      MIX_RATIO: 1.0
      RANDOM_N_VIEWS: true
      TRANSFORM:
        AUG: false
        TYPE: SimpleTransform3DMultiView
      URLS: data/dataset_tars/DexYCB_mv/DexYCB_mv_test-{000000..000003}.tar
      VIEW_RANGE:
      - 2
      - 2
    TYPE: MixWebDataset
DATA_PRESET:
  BBOX_EXPAND_RATIO: 2.0
  CENTER_IDX: 0
  HEATMAP_SIGMA: 2.0
  HEATMAP_SIZE:
  - 32
  - 32
  IMAGE_SIZE:
  - 256
  - 256
  NUM_JOINTS: 21
  NUM_VERTS: 778
  USE_CACHE: true
  WITH_HEATMAP: true
  WITH_MASK: false
MODEL:
  BACKBONE:
    FREEZE_BATCHNORM: true
    PRETRAINED: checkpoints/hrnetv2_w40_imagenet_pretrained.pth
    TYPE: HRNet
  HEAD:
    CAM_FEAT_MERGE: attn
    CENTER_SHIFT: true
    DEPTH_END: 1.2
    DEPTH_NUM: 32
    DEPTH_START: 0.0
    EMBED_DIMS: 256
    IN_CHANNELS: 160
    LID: false
    NUM_PREDS: 3
    NUM_QUERY: 799
    NUM_REG_FCS: 2
    N_SAMPLE: 4096
    POINTS_FEAT_DIM: 256
    POSITIONAL_ENCODING:
      NORMALIZE: true
      NUM_FEATS: 128
      TYPE: SinePositionalEncoding3D
    POSITION_RANGE:
    - -0.6
    - -0.6
    - 0.0
    - 0.6
    - 0.6
    - 1.2
    QUERY_TYPE: KPT
    RADIUS_SAMPLE: 0.1
    TRANSFORMER:
      BPS_FEAT_DIM: 4096
      DROPOUT: 0.1
      INPUT_FEAT_DIM: 256
      NUM_ATTENTION_HEADS: 4
      NUM_HIDDEN_LAYERS: 4
      N_BLOCKS: 3
      N_NEIGHBOR: 32
      N_NEIGHBOR_QUERY: 32
      PARAMETRIC_OUTPUT: false
      TRANSFORMER_CENTER_IDX: 9
      TYPE: PtEmbedTRv4
    TYPE: POEM_Generalized_Head
    WITH_MULTIVIEW: true
    WITH_POSITION: true
  LOSS:
    EDGE_LOSS_WEIGHT: 0.0
    HEATMAP_JOINTS_WEIGHT: 10.0
    JOINTS_2D_LOSS_WEIGHT: 1.0
    JOINTS_LOSS_TYPE: l2
    JOINTS_LOSS_WEIGHT: 1.0
    TRIANGULATED_JOINTS_WEIGHT: 10.0
    VERTICES_2D_LOSS_WEIGHT: 0.0
    VERTICES_LOSS_TYPE: l1
    VERTICES_LOSS_WEIGHT: 1.0
  PRETRAINED: null
  TYPE: PtEmbedMultiviewStereoV2
  VERTICES_INIT_MODE: linear_inv_skinning
TRAIN:
  BATCH_SIZE: 2
  CONV_REPEATABLE: true
  EPOCH: 1
  FIND_UNUSED_PARAMETERS: false
  GRAD_CLIP:
    NORM: 1.0
    TYPE: 2
  GRAD_CLIP_ENABLED: true
  LOG_INTERVAL: 10
  LR: 0.0001
  LR_DECAY_GAMMA: 0.1
  LR_DECAY_STEP:
  - 7
  MANUAL_SEED: 1
  OPTIMIZER: adam
  SCHEDULER: StepLR
  WEIGHT_DECAY: 0.0
